#!/bin/bash
set -e

# --- Prerequisite Checks ---
echo "Checking Docker status..."
if ! docker info &> /dev/null; then
    echo "Error: Docker is not running." && exit 1
fi
echo "Docker is running."

echo "Checking Minikube cluster status..."
if ! minikube status | grep -q "apiserver: Running"; then
    echo "Minikube cluster is not running. Starting..."
    minikube start --driver=docker --cpus=2 --memory=4096 || { echo "Error: Failed to start Minikube"; exit 1; }
fi
kubectl config use-context minikube || { echo "Error: Failed to set Minikube context"; exit 1; }
echo "Minikube cluster is running."

# --- Main Script ---

# 1. Clean up previous installations
echo "Cleaning up any existing application resources..."
helm uninstall my-react-app --ignore-not-found=true
rm -rf my-react-chart # Remove old chart directory to ensure a fresh start

# 2. Create and Configure a new Helm Chart
echo "Creating Helm chart..."
helm create my-react-chart

# 3. Create Helm values for the React app
echo "Creating Helm values for the React app..."
cat << EOF > my-react-chart/values.yaml
replicaCount: 2

image:
  repository: edydockers/rsschool
  pullPolicy: IfNotPresent
  tag: "latest"

# Add this serviceAccount block to fix the error
serviceAccount:
  # We don't need to create a separate service account for this app
  create: false
  # If you were to create one, you could specify annotations and a name here
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 9999

# Disable unused features
ingress:
  enabled: false
autoscaling:
  enabled: false
EOF

# 4. Adjust the default templates for your app's port
# <-- MODIFIED: The default templates need a small change for the non-80 port
echo "Adjusting Helm templates for port 9999..."
sed -i.bak 's/targetPort: http/targetPort: 9999/g' my-react-chart/templates/service.yaml
sed -i.bak 's/containerPort: 80/containerPort: 9999/g' my-react-chart/templates/deployment.yaml
rm my-react-chart/templates/*.bak # Clean up backup files made by sed

# 5. Deploy the Application using Helm
# <-- MODIFIED: Use helm install instead of kubectl apply
echo "Deploying the application with Helm..."
helm install my-react-app ./my-react-chart --wait --timeout 5m

echo "Application deployed successfully!"

# 6. Access the Application
# <-- MODIFIED: The service name is generated by Helm (<releasename>-<chartname>)
echo "--------------------------------------------------"
echo "To access your application, run this in a new terminal:"
echo "kubectl port-forward service/my-react-app-my-react-chart 8080:9999"
echo "Then open http://localhost:8080 in your browser."