name: Deploy K8s Cluster

on:
  push:
    branches:
      - task-3

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  setup_k8s:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Install kOps
        run: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.21.1/kops-linux-amd64
          chmod +x kops
          sudo mv kops /usr/local/bin/

      - name: kOps Cluster Deployment
        run: |
          kops create cluster --name=mycluster.k8s.local --zones=us-east-1a --yes
          kops update cluster --name mycluster.k8s.local --yes
