name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::981603173951:role/GithubActionsRole
          aws-region: us-east-1

      - name: Terraform Init
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          STATE_FILE_KEY: "dev/terraform.tfstate"
          AWS_REGION: "us-east-1"
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
        run: terraform init \
          -backend-config="bucket=${BUCKET_NAME}" \
          -backend-config="key=${STATE_FILE_KEY}" \
          -backend-config="region=${AWS_REGION}" \
          -backend-config="encrypt=true" \
          -backend-config="kms_key_id=${KMS_KEY_ID}"

      - name: Terraform Plan
        run: terraform plan