name: Deploy K8s Cluster

on:
  push:
    branches:
      - task-3.1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::981603173951:role/GithubActionsRole
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  setup_k8s:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::981603173951:role/GithubActionsRole
          aws-region: eu-west-1
          audience: sts.amazonaws.com

      - name: Install kOps
        run: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/v1.21.1/kops-linux-amd64
          chmod +x kops
          sudo mv kops /usr/local/bin/

      - name: kOps Cluster Deployment
        run: |
          export KOPS_STATE_STORE=s3://your-s3-bucket-name
          kops create cluster --name=mycluster.k8s.local --zones=eu-west-1a --yes
          kops update cluster --name mycluster.k8s.local --yes
